#!/usr/bin/python3
import zmq

context = zmq.Context()

#  Socket to talk to server
print("Connecting to hello world server")
socket = context.socket(zmq.REQ)

# socket.setsockopt(zmq.RCVTIMEO, 2000)
socket.connect("ipc:///root/unix_socket")

#  Do 10 requests, waiting each time for a response
for request in range(10):
    print("Sending request {}".format(request))
    socket.send(b"Hello")

    #  Get the reply.
    message = socket.recv()
    print("Received reply %s [ %s ]" % (request, message))
