#!/usr/bin/python3
import zmq
import os

#  Prepare our context and sockets
context = zmq.Context()
socket = context.socket(zmq.REQ)
socket.connect("tcp://proxy:5559")
client_id = os.environ["CLIENT_ID"]

#  Do 10 requests, waiting each time for a response
for request in range(1,11):
    socket.send("Hello {}".format(client_id).encode('ascii'))
    message = socket.recv()
    print("[CLIENT {}] Received reply {} [{}]".format(client_id, request, message))