version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: client.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: server.dockerfile
    environment:
      - PYTHONUNBUFFERED=1