#!/usr/bin/python3
import zmq

context = zmq.Context()
socket = context.socket(zmq.REP)
socket.connect("tcp://proxy:5560")

while True:
    message = socket.recv()
    print("Received request: %s" % message)
    socket.send(b"World")