#!/usr/bin/python3
import zmq
import time
from random import randrange

context = zmq.Context()
socket = context.socket(zmq.PUB)
socket.bind("tcp://*:5556")
print("Starting Pub process")

while True:
    zipcode = randrange(1,4)
    temperature = randrange(-80, 135)
    relhumidity = randrange(10, 60)

    msg = "%i %i %i" % (zipcode, temperature, relhumidity)
    print("Sending string: {}".format(msg))
    socket.send_string("%i %i %i" % (zipcode, temperature, relhumidity))
    time.sleep(1)
