version: '3'
services:
  server:
    build:
      context: .
      dockerfile: server.dockerfile
    environment:
      - PYTHONUNBUFFERED=1

  # client:
  #   build:
  #     context: .
  #     dockerfile: client.dockerfile