#!/usr/bin/python3
import time
import zmq
from threading import Thread

context = zmq.Context()

def server():
	socket = context.socket(zmq.REP)
	socket.bind("inproc://local_name")
	print("Starting ZMQ Server")

	while True:
	    #  Wait for next request from client
	    message = socket.recv()
	    print("Received request: %s" % message)

	    #  Do some 'work'
	    time.sleep(1)

	    #  Send reply back to client
	    socket.send(b"World")

def client():
	#  Socket to talk to server
	print("Connecting to hello world server")
	socket = context.socket(zmq.REQ)
	socket.connect("inproc://local_name")

	#  Do 10 requests, waiting each time for a response
	for request in range(10):
	    print("Sending request {}".format(request))
	    socket.send(b"Hello")

	    #  Get the reply.
	    message = socket.recv()
	    print("Received reply %s [ %s ]" % (request, message))


def main():
	# Start the server in a new thread
	thread = Thread(target = server)
	thread.start()

	# Execute the client in a new thread
	client()

if __name__ == "__main__":
	main()




